### ISSUE TITLE
[Major Refactor] Need to split geofire-android and geofire-java into two repos

### ISSUE THREAD

**Issue by vijaysimhajoshi** [firebase/geofire-java#28]
When trying to set the setLocation on the GeoFire object runs into following issue at run time

```
No virtual method setValue(Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/firebase/tasks/Task; in class Lcom/google/firebase/database/DatabaseReference; or its super classes (declaration of 'com.google.firebase.database.DatabaseReference' appears in  (apk file )
```

Using the GeoFire 2.0.0 SNAPSHOT version.
Firebase version: com.google.firebase:firebase-database:9.0.2

**Comment by samtstern** [comment]
@jdimond @abehaskins I am seeing this as well when trying to use the geofire-2 branch in an Android app.

The problem is this block in GeoFire.java
```
        if (completionListener != null) {
            keyRef.setValue(updates, geoHash.getGeoHashString(), new DatabaseReference.CompletionListener() {
                @Override
                public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
                    completionListener.onComplete(key, databaseError);
                }
            });
        } else {
            keyRef.setValue(updates, geoHash.getGeoHashString());
        }
```

Specifically the crash is at this line:
```
            keyRef.setValue(updates, geoHash.getGeoHashString());
```

**Comment by samtstern** [comment]
Fixed be #34

**Comment by ruud-j** [comment]
Dus bug still seams to appear on 2.1.0 using firebase-database 9.4.0. Any ideas?

**Comment by MrIceman** [comment]
any fix yet?

**Comment by orzsikodon** [comment]
hi, this bug is still present. Any news on the update?

**Comment by andronicus-kim** [comment]
@orzsikodon Hi, i added the Completion listener but i still run into the same bug.

**Comment by horgag1** [comment]
any update on this?

**Comment by habeebrahmanpt** [comment]
com.firebase:geofire-android:2.3.0'  have this problem

**Comment by samtstern** [comment]
This looks very similar to #133 ... but I have not been able to reproduce it in a long time so I am not sure how to fix it.  If anyone could send along an [MCVE](https://stackoverflow.com/help/mcve) that would be amazing.

**Comment by samtstern** [comment]
@DongNH4 @habeebrahmanpt can you show me your `dependencies` from `app/build.gradle`?

**Comment by umarhussain15** [comment]
Please see the dependencies list: 
```
    implementation 'com.google.firebase:firebase-core:12.0.1'
    implementation "com.google.firebase:firebase-auth:12.0.1"
    implementation "com.google.firebase:firebase-database:12.0.1"
    implementation "com.google.android.gms:play-services-auth:12.0.1"
    implementation "com.google.android.gms:play-services-maps:12.0.1"
    implementation "com.google.android.gms:play-services-location:12.0.1"
    implementation "com.google.android.gms:play-services-places:12.0.1"
    implementation 'com.firebase:geofire-android:2.3.1'
```

**Comment by samtstern** [comment]
@umarhussain15 looks like you updated to `2.3.1` which was released today, are you still seeing this issue?  Also does your app use ProGuard?

**Comment by umarhussain15** [comment]
Yes still the issue is present with 2.3.1. proguard is set to true in debug

**Comment by samtstern** [comment]
@umarhussain15 can you try disabling proguard and seeing if the issue persists?

**Comment by umarhussain15** [comment]
It still persist. I manually tried the functionality of setLocation that is working fine here is the code snippet:

```
// working
GeoHash geoHash = new GeoHash(new GeoLocation(location.getLatitude(),location.getLongitude()));
Map<String, Object> updates = new HashMap<>();
updates.put("g", geoHash.getGeoHashString());
updates.put("l", Arrays.asList(location.getLatitude(),location.getLongitude()));
geoFire.getDatabaseReference().child(firebaseUser.getUid()).setValue(updates,geoHash.getGeoHashString());
// not working
//geoFire.setLocation(firebaseUser.getUid(), new GeoLocation(location.getLatitude(),location.getLongitude())); 
```

I used the firebase reference from geofire just to test if that was the issue but it works when tried manually.

**Comment by samtstern** [comment]
@umarhussain15 damn ok well thank you for trying!  I will have to think about what could be the root cause here.

**Comment by viksoffice** [comment]
Today is 4/19/2018 but still same problem :(

**Comment by maher640** [comment]
21/04/2018
The error still happening also when removing the location `removeLocation(key)` and doesn't work unless the listener is provided.

**Comment by HusDev** [comment]
I change it from `com.firebase:geofire-android:3.1.0`  to  `com.firebase:geofire-android:2.1.1` 
works fine :)

**Comment by ashu-mkb** [comment]
i am having the same issue. please help i need to keep proguard and i am time bound.

**Comment by ashu-mkb** [comment]
This issue is only arising with proguard. But i need to keep proguard to safeguard (somewhat) other logic inside. Please help its very urgent. Also, by downgrading dependency to 2.1.1, geoquery seems to be not working. I am not explicitly using setLocation etc, i am only using geofire to query location. Please help!

**Comment by ashu-mkb** [comment]
@zezi Thank you so much! Though i tried earlier to add exception in proguard, i failed to achieve the desired result. This fixed my problem. Thank you again!!!

**Comment by Dilshan97** [comment]
> I change it from `com.firebase:geofire-android:3.1.0` to `com.firebase:geofire-android:2.1.1`
> works fine :)

Yeah it's works for me :-) Thank you

**Comment by samtstern** [comment]
Thanks @abelthefirst for laying it out so clearly.  This seems to be a fundamental issue with how this library is structured and published.  IMO the only way forward would be to make separate geofire-java and geofire-android libraries (no shared source, maybe a shared published dependency) but that's more effort than I can spare right now :-/

**Comment by umarhussain15** [comment]
@samtstern I have extracted the geofire library as library module for android. Its working correctly but I am having difficulty in making test cases successful. My understanding is that you have written test with admin sdk for java. In case of Android I was looking for using android test so that the context is available.
Can you guide on how to convert the test cases for android library? 
Here is the link to my repo:
https://github.com/umarhussain15/geofire-android

**Comment by Stevemoretz** [comment]
It still doesn't work in 2019.Without the listeners.

**Comment by samtstern** [comment]
@umarhussain15 wow geofire-android is really cool!  Sorry I missed this in my inbox the first time.

I think splitting this up into Android and Java libraries with separate repos is the only way forward, but unfortunately I don't have the time to handle such a big project right now.

As for the test cases I suspect we will have to do something different on Android.  Maybe use the regular Android SDK but sign in with a custom token?

**Comment by emailsubjekt** [comment]
> @umarhussain15 wow geofire-android is really cool! Sorry I missed this in my inbox the first time.
> 
> I think splitting this up into Android and Java libraries with separate repos is the only way forward, but unfortunately I don't have the time to handle such a big project right now.
> 
> As for the test cases I suspect we will have to do something different on Android. Maybe use the regular Android SDK but sign in with a custom token?

What are you talking about? Is there still not a solution for this. I keep getting this error from time to time. This can't happen in an app!

**Comment by umarhussain15** [comment]
@emailsubjekt please have a look at https://github.com/umarhussain15/geofire-android. I have extracted the library specifically as android module to avoid the issues mention in this thread. It in working state and can be easily plugged in place of geofire-java.

**Comment by emailsubjekt** [comment]
> @emailsubjekt please have a look at https://github.com/umarhussain15/geofire-android. I have extracted the library specifically as android module to avoid the issues mention in this thread. It in working state and can be easily plugged in place of geofire-java.

Is this official or a workaround?

**Comment by samtstern** [comment]
@emailsubjekt it's a workaround but I officially recommend it for now!  @umarhussain15 has done the right thing.

**Comment by samtstern** [comment]
I have finally gotten the time to take this on.  I am going to:

1. Make a new repository called `geofire-android` that ships an android-only version of this library.
2. Convert this repository to be java-admin only and remove the android module from here.
3. Republish both libraries at a new major version.

**Comment by emailsubjekt** [comment]
> @emailsubjekt please have a look at https://github.com/umarhussain15/geofire-android. I have extracted the library specifically as android module to avoid the issues mention in this thread. It in working state and can be easily plugged in place of geofire-java.

Thanks!
